---
- name: set backup_path fact
  set_fact:
    backup_path: "/root/backup"

- name: Pull Job Templates from Tower
  uri:
    url: "https://tower2/api/v1/job_templates/"
    user: "{{ tower_admin }}"
    password: "{{ tower_password }}"
    body_format: json
    method: GET
    validate_certs: no
  register: job_templates

- name: Remove config file if it exists
  file:
    path: "{{backup_path}}/job_templates.config"
    state: absent

- name: Create Job Templates Backup File
  shell: |
    echo "  - name: {{item.0}}" >> "{{backup_path}}/job_templates.config"
    echo "    description: {{item.1}}" >> "{{backup_path}}/job_templates.config"
    echo "    inventory: {{item.2}}" >> "{{backup_path}}/job_templates.config"
    echo "    project:  {{item.3}}" >> "{{backup_path}}/job_templates.config"
    echo "    playbook: {{item.4}}" >> "{{backup_path}}/job_templates.config"
    echo "    credential: {{item.5}}" >> "{{backup_path}}/job_templates.config"
    echo "    cloud_credential: {{item.6}}" >> "{{backup_path}}/job_templates.config"
    echo "    network_credential: {{item.7}}" >> "{{backup_path}}/job_templates.config"
    echo "    job_type: {{item.8}}" >> "{{backup_path}}/job_templates.config"
    echo -e "    become_enabled: {{item.9}}\n" >> "{{backup_path}}/job_templates.config"
  with_together:
    - "{{job_templates|json_query('json.results[].name')}}"
    - "{{job_templates|json_query('json.results[].description')}}"
    - "{{job_templates|json_query('json.results[].summary_fields.inventory.name')}}"
    - "{{job_templates|json_query('json.results[].summary_fields.project.name')}}"
    - "{{job_templates|json_query('json.results[].playbook')}}"
    - "{{job_templates|json_query('json.results[].summary_fields.credential.name')}}"
    - "{{job_templates|json_query('json.results[].summary_fields.cloud_credential.name')}}"
    - "{{job_templates|json_query('json.results[].summary_fields.network_credential.name')}}"
    - "{{job_templates|json_query('json.results[].job_type')}}"
    - "{{job_templates|json_query('json.results[].become_enabled')}}"
