---

- name: Pull Job Templates from Tower
  uri:
    url: "https://tower2/api/v1/job_templates/"
    user: "{{ tower_admin }}"
    password: "{{ tower_password }}"
    body_format: json
    method: GET
    validate_certs: no
  register: job_templates

#- name: "Display all template names"
#  debug: var=job_templates
  #debug: var=(job_templates|type_debug)
  #with_items: "{{ job_templates|type_debug }}"
- name: Create Job Template Backup File
  template:
    src: job_templates.j2
    dest: /root/job_templates.config


- name: "Display all template names"
  #debug: var=job_templates
  debug: msg="Name={{item.0}}, Project={{item.1}}"
  with_together: 
    - "{{job_templates|json_query('json.results[].name')}}"
    - "{{job_templates|json_query('json.results[].summary_fields.project.name')}}"
    - "{{job_templates|json_query('json.results[].summary_fields.inventory.name')}}"
    - "{{job_templates|json_query('json.results[].summary_fields.cloud_credential.name')}}"
    - "{{job_templates|json_query('json.results[].summary_fields.credential.name')}}"
    - "{{job_templates|json_query('json.results[].summary_fields.network_credential.name')}}"
    - "{{job_templates|json_query('json.results[].job_type')}}"
    - "{{job_templates|json_query('json.results[].playbook')}}"
    - "{{job_templates|json_query('json.results[].become_enabled')}}"
  #with_items: "{{ job_templates }}"
  tags: skip
