---

- name: Pull Job Templates from Tower
  uri:
    url: "https://tower2/api/v1/job_templates/"
    user: "{{ tower_admin }}"
    password: "{{ tower_password }}"
    body_format: json
    method: GET
    validate_certs: no
  register: job_templates

#- name: "Display all template names"
#  debug: var=job_templates
  #debug: var=(job_templates|type_debug)
  #with_items: "{{ job_templates|type_debug }}"
  
- name: "Display all template names"
  #debug: var=job_templates
  debug: var=item
  with_together: 
    - "{{job_templates|json_query('json.results[].name')}}"
    - "{{job_templates|json_query('json.results[].summary_fields.project.name')}}"
  #with_items: "{{ job_templates }}"
