---

- name: Pull Job Templates from Tower
  uri:
    url: "https://tower2/api/v1/job_templates/"
    username: admin
    password: "{{ tower_password }}"
    body_format: json
    method: GET
    validate_certs: no
  register: job_templates
  
- name: "Display all template names"
  debug: var=item
  with_items: "{{results|json_query('Name')}}"
