---

- name: Pull Job Templates from Tower
  uri:
    url: "https://tower2/api/v1/job_templates/"
    user: "{{ tower_admin }}"
    password: "{{ tower_password }}"
    body_format: json
    method: GET
    validate_certs: no
  register: job_templates
  
- name: "Display all template names"
  debug: var=item
  #with_items: "{{job_templates|json_query('results.Name')}}"
  with_items: "{{ job_templates }}"
