---

- name: Pull Job Templates from Tower
  uri:
    url: "https://tower2/api/v1/projects/"
    user: "{{ tower_admin }}"
    password: "{{ tower_password }}"
    body_format: json
    method: GET
    validate_certs: no
  register: projects

- name: Remove config file if it exists
  file:
    path: /root/backup/projects.config
    state: absent

- name: Create Project Heading
  shell: echo "Tower_Projects:" >> /root/backup/projects.config

- name: Create Job Templates Backup File
  shell: |
    echo "  - name: {{item.0}}" >> /root/backup/projects.config
    echo "    description: {{item.1}}" >> /root/backup/projects.config
    echo "    scm_type: {{item.2}}" >> /root/backup/projects.config
    echo "    scm_url:  {{item.3}}" >> /root/backup/projects.config
    echo "    scm_branch: {{item.4}}" >> /root/backup/projects.config
    echo "    scm_credential: {{item.5}}" >> /root/backup/projects.config
    echo "    scm_clean: {{item.6}}" >> /root/backup/projects.config
    echo "    scm_update_on_launch: {{item.7}}" >> /root/backup/projects.config
    echo "    scm_update_cache_timeout: {{item.8}}" >> /root/backup/projects.config
    echo "    scm_delete_on_update: {{item.9}}" >> /root/backup/projects.config
    echo -e "    organization: {{item.10}}\n" >> /root/backup/projects.config
  with_together:
    - "{{projects|json_query('json.results[].name')}}"
    - "{{projects|json_query('json.results[].description')}}"
    - "{{projects|json_query('json.results[].scm_type')}}"
    - "{{projects|json_query('json.results[].scm_url')}}"
    - "{{projects|json_query('json.results[].scm_branch')}}"
    - "{{projects|json_query('json.results[].scm_credential')}}"
    - "{{projects|json_query('json.results[].scm_clean')}}"
    - "{{projects|json_query('json.results[].scm_update_on_launch')}}"
    - "{{projects|json_query('json.results[].scm_update_cache_timeout')}}"
    - "{{projects|json_query('json.results[].scm_delete_on_update')}}"
    - "{{projects|json_query('json.results[].summary_fields.organization.name')}}"
